name: Scrape Data

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Debug environment
        run: |
          pwd
          ls -la
          npm list
        
      - name: Run scraper
        run: node scraper.js
        
      - name: Check if data.json exists
        run: |
          if [ -f "data.json" ]; then
            echo "data.json exists"
            cat data.json | head -n 20
          else
            echo "data.json does not exist"
            ls -la
          fi
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data"
          git push